export async function onRequestPost(context) {
  const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type","Content-Type":"application/json"};
  try{
    const body=await context.request.json();
    for(const key of ["domain","task","baseline","objective"]){if(!body[key]||!String(body[key]).trim())return new Response(JSON.stringify({error:`Missing required field: ${key}`}),{status:400,headers:cors})}
    const apiKey=context.env.OPENAI_API_KEY;if(!apiKey)return new Response(JSON.stringify({error:"OPENAI_API_KEY is not configured. Add it as a Cloudflare secret."}),{status:500,headers:cors});
    const model=context.env.OPENAI_MODEL||"gpt-6-luna";
    const safe={specialNeed:body.specialNeed||"",degree:body.degree||"",associated:body.associated||"",languages:body.languages||"",significant:body.significant||"",services:body.services||"",relaxations:body.relaxations||"",domain:body.domain||"",task:body.task||"",baseline:body.baseline||"",objective:body.objective||"",setting:Array.isArray(body.setting)?body.setting:[],tlm:body.tlm||"",strategies:body.strategies||"",procedure:body.procedure||"",adaptations:body.adaptations||"",evaluation:body.evaluation||"",classSection:body.classSection||""};
    const systemPrompt=`You are an experienced Special Educator helping draft an Individualised Education Plan (IEP). Use only the teacher-supplied information. Do not invent diagnoses, test scores, disability severity, legal entitlements, or CBSE relaxations. Write practical, observable, measurable educational goals. The annual goal must connect directly to the baseline and target skill. Create 4 short-term goals that progress logically from the baseline to the annual target. Give each short-term goal a suggested timeframe such as 2 weeks, 4 weeks, 6 weeks, 8–10 weeks, etc. Adjust duration when task complexity warrants it. Timeframes are professional suggestions, not official rules. Use condition/skill/criterion/measurement style where supported. Prefer independence and reduction of prompts when appropriate, but do not assume a prompt level not supplied. Suggest evaluation/measurement, teaching strategies, teaching procedure, adaptations/accommodations/modifications and TLM when supported. Do not use stigmatizing language. Return ONLY valid JSON in this exact shape: {"annual_goal":"string","short_term_goals":[{"timeframe":"string","goal":"string","measurement":"string"},{"timeframe":"string","goal":"string","measurement":"string"},{"timeframe":"string","goal":"string","measurement":"string"},{"timeframe":"string","goal":"string","measurement":"string"}],"timeframe_note":"string","tlm":"string","teaching_strategies":"string","teaching_procedure":"string","adaptations":"string","evaluation":"string"}`;
    const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Authorization":`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model,input:[{role:"system",content:[{type:"input_text",text:systemPrompt}]},{role:"user",content:[{type:"input_text",text:`Teacher's IEP information:\n${JSON.stringify(safe,null,2)}`}] }],temperature:0.2,max_output_tokens:1800})});
    const raw=await response.json();if(!response.ok)return new Response(JSON.stringify({error:raw?.error?.message||"OpenAI API request failed."}),{status:response.status,headers:cors});
    let text="";if(typeof raw.output_text==="string")text=raw.output_text;else if(Array.isArray(raw.output))for(const item of raw.output){if(!Array.isArray(item.content))continue;for(const part of item.content)if(part.type==="output_text"&&typeof part.text==="string")text+=part.text}
    text=text.trim().replace(/^```json\s*/i,"").replace(/```$/i,"").trim();let result;try{result=JSON.parse(text)}catch{return new Response(JSON.stringify({error:"The AI returned an unexpected format. Please try again."}),{status:502,headers:cors})}
    return new Response(JSON.stringify(result),{status:200,headers:cors});
  }catch(e){return new Response(JSON.stringify({error:"Unexpected server error."}),{status:500,headers:cors})}
}
export async function onRequestOptions(){return new Response(null,{status:204,headers:{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type","Access-Control-Allow-Methods":"POST, OPTIONS"}})}
